name: Frontend Deploy Dev

on:
  push:
    branches: [ develop ]

jobs:
  deploy-dev:
    uses: ./.github/workflows/ftp-deploy.yml
    secrets: inherit
    with:
      environment: dev
      local-dir: frontendVersion1/
